apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsa-creditcard-service-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsa-creditcard-service-v1
  template:
    metadata:
      labels:
        app: rsa-creditcard-service-v1
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always